## Table de catégorisation
categ <- tibble::tribble(
  ~indicateur,                                                                                    ~nom_indicateur, ~TD, ~D, ~I, ~F,
  "A1",                                                                  "Diversité des espèces cultivées",  NA,  0,  3,  4,
  "A2",                                                                              "Diversité génétique",  NA,  0,  2,  4,
  "A3",                                                                "Diversité temporelle des cultures",  NA,  0,  3,  5,
  "A4",                                                               "Qualité de l'organisation spatiale",  NA,  0,  3,  5,
  "A5",                              "Gestion des insectes pollinisateurs et des auxiliaires des cultures",  NA,  0,  2,  4,
  "A6",                                   "Autonomie en énergie, matériaux, matériels, semences et plants",  NA,  0,  3,  5,
  "A7",                                                               "Autonomie alimentaire de l’élevage",  NA,  0,  4,  7,
  "A8",                                                                               "Autonomie en azote",  NA,  0,  3,  7,
  "A9",                                        "Sobriété dans l'usage de l'eau et partage de la ressource",  NA,  0,  4,  6,
  "A10",                                                         "Sobriété dans l'utilisation du phosphore",  NA,  0,  4,  8,
  "A11",                                                         "Sobriété dans la consommation en énergie",  NA,  0,  3,  6,
  "A12",                                                                 "Raisonner l'utilisation de l'eau",  NA,  0,  5,  8,
  "A13",                                                                    "Favoriser la fertilité du sol",  NA,  0,  5,  7,
  "A14",                    "Maintenir l’efficacité de la protection sanitaire des cultures et des animaux",  NA,  0,  2,  4,
  "A15",                                    "Sécuriser la disponibilité des moyens matériels de production",  -4,  0,  2,  4,
  "A16",                                           "Réduire l'impact des pratiques sur la qualité de l'eau",  -2,  0,  3,  5,
  "A17",                                          "Réduire l'impact des pratiques sur la  qualité de l'air",  NA,  0,  3,  5,
  "A18",                                      "Réduire l'impact des pratiques sur le changement climatique",  NA,  0,  2,  5,
  "A19",                         "Réduire l'usage des produits phytosanitaires et traitements vétérinaires",  NA, -1,  3,  5,
  "B1",                                                         "Production alimentaire de l'exploitation",  NA,  0,  3,  6,
  "B2",                                                   "Contribution à l’équilibre alimentaire mondial",  NA,  0,  4,  6,
  "B3",                                                             "Qualité de la production alimentaire",  NA,  0,  1,  5,
  "B4",                                                                            "Pertes et gaspillages",  NA,  0,  2,  4,
  "B5",                                          "Liens sociaux, hédoniques et culturels à l'alimentation",  NA,  0,  3,  6,
  "B6",                "Engagement dans des démarches environnementales contractualisées et territoriales",  NA,  0,  3,  5,
  "B7",                                                                 "Services marchands au territoire",  NA,  0,  2,  4,
  "B8",                                   "Valorisation des produits par filières courtes ou de proximité",  NA,  0,  1,  3,
  "B9",                                                              "Valorisation des ressources locales",  NA,  0,  1,  3,
  "B10", "Valorisation et qualité du patrimoine : bâti, paysage et savoirs locaux et ressources naturelles",  NA,  0,  1,  2,
  "B11",                                                                        "Accessibilité de l’espace",  NA,  0,  1,  3,
  "B12",                                                               "Gestion des déchets non organiques",  NA, -1,  1,  2,
  "B13",                                                "Réseaux d'innovation et mutualisation du matériel",  NA,  0,  2,  4,
  "B14",                                                   "Contribution à l'emploi et gestion du salariat",  NA,  0,  1,  3,
  "B15",                                                                         "Mutualisation du travail",  NA,  0,  1,  4,
  "B16",                                                                  "Intensité et qualité au travail",  -7,  0,  4,  8,
  "B17",                                                                     "Accueil, hygiène et sécurité",  NA,  0,  1,  3,
  "B18",                                                                                        "Formation",  NA,  0,  1,  4,
  "B19",                                                  "Implication sociale territoriale et solidarités",  NA, -2,  2,  3,
  "B20",                                                                         "Démarche de transparence",  NA,  0,  2,  4,
  "B21",                                                                                   "Qualité de vie",  NA,  0,  2,  5,
  "B22",                                                                                        "Isolement",  NA,  0,  3,  5,
  "B23",                                                                                 "Bien-être animal",  NA,  0,  3,  5,
  "C1",                                                                              "Capacité économique",  NA,  0, 10, 17,
  "C2",                                                                                "Poids de la dette",  NA,  0,  4, 12,
  "C3",                                                                    "Taux d'endettement structurel",  NA,  0,  3,  6,
  "C4",                                                                       "Diversification productive",  NA,  0,  4,  8,
  "C5",                                                      "Diversification et relations contractuelles",  NA, -2,  6,  7,
  "C6",                                                                            "Sensibilité aux aides",   0,  2,  4,  6,
  "C7",                           "Contribution des revenus extérieurs à l'indépendance de l'exploitation",  NA, NA,  0,  4,
  "C8",                                                                      "Transmissibilité économique",   0,  2,  6, 10,
  "C9",                                                                               "Pérennité probable",  NA,  0,  4,  6,
  "C10",                                                          "Efficience brute du processus productif",  NA,  0,  6, 10,
  "C11",                                                 "Sobriété en intrants dans le processus productif",  NA,  0,  4,  6
)


## Légende associée aux métadonnées du fichier .json
MTD_legende <- tibble::tribble(
  ~code,                                   ~nom,                                                      ~etendue,
  "MTD_00",      "Version du calculateur utilisée",                                                    "Alpha 10",
  "MTD_01",             "Identifiant exploitation",                                                       "Num 6",
  "MTD_02",                                  "SAU",                                           "0 à 10 000 (2 dc)",
  "MTD_03",                                  "UTH",                                           "0 à 10 000 (2 dc)",
  "MTD_04",                                "UTH F",                                              "0 à 100 (2 dc)",
  "MTD_05", "Tranche d’âge du chef d’exploitation", "«-25»,«25-35»,«35-45», «45-55»,«55-65» et «65+»",
  "MTD_06",      "Typologie d'exploitation (OTEX)",                                       "Codes OTEX simplifiés",
  "MTD_07",      "Surface en herbe en % de la SAU",                                              "0 à 100 (2 dc)",
  "MTD_08",               "Capital d’exploitation",                                             "0 à 100000 000",
  "MTD_09",                                  "EBE",                                    "– 1000 000 à 10000 000",
  "MTD_10",                     "Résultat courant",                                    "– 1000 000 à 10000 000",
  "MTD_11",      "Zone géographique (département)",                                      "liste des départements",
  "MTD_12",         "Atelier hors sol: oui / non",                                                      "0 ou 1",
  "MTD_13",                      "Année d'enquête",                                                       "Num 4",
  "MTD_14",                       "Type d’élevage",       "0 - pas d’élevage / 1 – monogastrique / 2 - herbivore",
  "MTD_15",              "Part des PP dans la SAU",                                              "0 à 100 (2 dc)",
  "MTD_16", "Usage des produits phytos: oui /non",                                                      "0 ou 1"
)
