#' Generate adequate plots for the dimension approach of the IDEA method
#'
#' @param IDEAdata output generated by an `importIDEA()` call
#'
#' @return a named list of plots
#' @importFrom magrittr %>%
#' @importFrom dplyr group_by summarise ungroup mutate inner_join arrange desc rowwise filter
#' @importFrom ggplot2 ggplot aes geom_bar position_dodge geom_hline scale_fill_manual geom_label theme element_blank theme_bw element_line element_text element_rect labs guides coord_flip facet_wrap
#' @importFrom purrr map2 map
#' @importFrom readr parse_number
#' @importFrom stringr str_remove_all
#' @importFrom tidyr nest
#' @export
#'
#' @examples
#' library(IDEATools)
#' path <- system.file("example_json.json", package = "IDEATools")
#' IDEAdata <- importIDEA(path, anonymous = FALSE)
#' IDEAres <- dimensionsPlots(IDEAdata)
dimensionsPlots <- function(IDEAdata) {

  Encoding(list_max_compo$composante) <- "UTF-8"

  singleplots <- function(res_dim) {
    splotlist <- list()

    dim_dimensions <- res_dim %>%
      group_by(dimension) %>%
      summarise(dimension_value = unique(dimension_value), max_dim = 100) %>%
      ungroup() %>%
      mutate(dimension = factor(dimension, levels = c("Agroécologique", "Socio-Territoriale", "Economique")))

    critiq <- min(res_dim$dimension_value)

    splotlist$dimensions <- ggplot(dim_dimensions, aes(x = dimension, y = dimension_value, group = factor(dimension))) +
      geom_bar(aes(x = dimension, y = max_dim, fill = dimension), alpha = 0.3, color = "black", position = position_dodge(width = 0.8), stat = "identity") +
      geom_bar(aes(fill = dimension), color = "black", position = position_dodge(width = 0.8), stat = "identity") +
      geom_hline(yintercept = critiq, color = "red", size = 1.5, linetype = 5) +
      scale_fill_manual(values = c("Agroécologique" = "#2e9c15", "Socio-Territoriale" = "#5077FE", "Economique" = "#FE962B")) +
      geom_label(aes(label = paste0(dimension_value, "/", max_dim)), fill = "white", size = 5) +
      theme(axis.line = element_blank()) +
      theme_bw() +
      theme(panel.grid.major.y  = element_line(color = "grey90"),
            panel.grid.major.x = element_blank()) +
      theme(
        axis.title.x = element_blank(),
        legend.text = element_text(size = 13),
        legend.title = element_text(size = 15),
        strip.text = element_text(size = 9, face = "bold")
      ) +
      theme(strip.background = element_rect(fill = "white", color = "black")) +
      theme(axis.text = element_text(size = 15, color = "black"), axis.title = element_text(size = 15, face = "bold")) +
      labs(fill = "Dimension", y = "Valeur de la dimension / valeur max") +
      theme(plot.caption = element_text(face = "bold")) +
      theme(legend.position = "bottom") +
      guides(fill = FALSE)





    ae_levels <- c("Diversité fonctionnelle", "Bouclage de flux de matières et d'énergie \npar une recherche d'autonomie", "Sobriété dans l'utilisation des ressources", "Assurer des conditions favorables à la production\n à moyen et long terme", "Réduire les impacts sur la santé humaine et les écosystèmes")

    st_levels <- c("Alimentation", "Développement local \net économie circulaire", "Emploi et qualité au travail", "Ethique et développement humain")

    ec_levels <- c("Viabilité économique et financière", "Indépendance", "Transmissibilité", "Efficience globale")


    glob_levels <- c(ae_levels, st_levels, ec_levels)


    dim_compo <- res_dim %>%
      inner_join(list_max_compo, by = "composante") %>%
      mutate(dim = sub("^([[:alpha:]]*).*", "\\1", indicateur)) %>%
      mutate(composante = ifelse(composante == "Assurer des conditions favorables à la production à moyen et long terme",
        yes = "Assurer des conditions favorables à la production\n à moyen et long terme", no = composante
      )) %>%
      mutate(composante = ifelse(composante == "Bouclage de flux \nde matières et d'énergie \npar une recherche d'autonomie",
        yes = "Bouclage de flux de matières et d'énergie \npar une recherche d'autonomie", no = composante
      )) %>%
      group_by(composante) %>%
      summarise(dim = unique(dim), max_compo = unique(max_compo), dimension = unique(dimension), composante_value = unique(composante_value)) %>%
      ungroup() %>%
      arrange(desc(dim)) %>%
      mutate(composante = factor(composante, levels = rev(glob_levels)))

    splotlist$composantes <- ggplot(dim_compo, aes(x = composante, y = composante_value, group = factor(dimension))) +
      geom_bar(aes(x = composante, y = max_compo, fill = dimension), alpha = 0.3, color = "black", position = position_dodge(width = 0.8), stat = "identity") +
      geom_bar(aes(fill = dimension), color = "black", position = position_dodge(width = 0.8), stat = "identity") +
      geom_label(aes(label = paste0(composante_value, "/", max_compo)), fill = "white", size = 5.5) +
      scale_fill_manual(values = c("Agroécologique" = "#2e9c15", "Socio-Territoriale" = "#5077FE", "Economique" = "#FE962B")) +
      theme(axis.line = element_blank()) +
      theme_bw() +
      theme(panel.grid.major.x  = element_line(color = "grey90"),
            panel.grid.major.y = element_blank()) +
      theme(panel.grid.minor.x = element_line(color = "grey90"),
            panel.grid.minor.y = element_blank()) +
      theme(
        axis.title.y = element_blank(),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 17),
        strip.text = element_text(size = 9, face = "bold")
      ) +
      theme(strip.background = element_rect(fill = "white", color = "black")) +
      theme(axis.text = element_text(size = 17, color = "black"), axis.title = element_text(size = 17, face = "bold")) +
      labs(fill = "Dimension", y = "Valeur de la composante / valeur max") +
      theme(legend.position = "bottom") +
      coord_flip()

    dim_indic <- res_dim %>%
      inner_join(list_max_compo, by = "composante") %>%
      inner_join(label_nodes, by = c("indicateur" = "code_indicateur", "composante", "dimension")) %>%
      rowwise() %>%
      mutate(composante = ifelse(composante == "Assurer des conditions favorables à la production à moyen et long terme",
        yes = "Assurer des conditions favorables à la production\n à moyen et long terme", no = composante
      )) %>%
      mutate(composante = ifelse(composante == "Bouclage de flux \nde matières et d'énergie \npar une recherche d'autonomie",
        yes = "Bouclage de flux de matières et d'énergie \npar une recherche d'autonomie", no = composante
      )) %>%
      mutate(composante = ifelse(composante == "Réduire les impacts sur la santé humaine et les écosystèmes",
        yes = "Réduire les impacts sur la santé humaine\n et les écosystèmes", no = composante
      )) %>%
      mutate(nom_indicateur = wrapit(nom_complet)) %>%
      ungroup() %>%
      inner_join(list_max, by = "indicateur") %>%
      filter(indicateur %in% liste_indicateurs) %>%
      mutate(num_indic = parse_number(indicateur)) %>%
      arrange(desc(dimension), desc(num_indic)) %>%
      mutate(indicateur = factor(indicateur, levels = unique(indicateur))) %>%
      mutate(nom_indicateur = factor(nom_indicateur, levels = unique(nom_indicateur))) %>%
      mutate(dimension2 = dimension) %>%
      group_by(dimension2) %>%
      nest()


    indic_plot <- function(dimension2, df) {
      if (dimension2 == "Socio-Territoriale") {
        lev <- st_levels
      }
      if (dimension2 == "Economique") {
        lev <- ec_levels
      }
      if (dimension2 == "Agroécologique") {
        lev <- c("Diversité fonctionnelle", "Bouclage de flux de matières et d'énergie \npar une recherche d'autonomie", "Sobriété dans l'utilisation des ressources", "Assurer des conditions favorables à la production\n à moyen et long terme", "Réduire les impacts sur la santé humaine\n et les écosystèmes")
      }

      df <- df %>%
        mutate(composante = factor(composante, levels = rev(lev))) %>%
        mutate(code_compo = as.numeric(composante)) %>%
        mutate(composante = paste0("Composante : ", composante, " (", composante_value, "/", max_compo, ")")) %>%
        arrange(code_compo) %>%
        mutate(composante = factor(composante, levels = rev(unique(composante))))



      ggplot(df, aes(x = nom_indicateur, y = value, fill = dimension)) +
        geom_bar(aes(x = nom_indicateur, y = valeur_max, fill = dimension), alpha = 0.3, color = "black", position = position_dodge(width = 0.8), stat = "identity") +
        geom_bar(aes(fill = dimension), color = "black", position = position_dodge(width = 0.8), stat = "identity") +
        facet_wrap(~composante, ncol = 1, scales = "free_y") +
        scale_fill_manual(values = c("Agroécologique" = "#2e9c15", "Socio-Territoriale" = "#5077FE", "Economique" = "#FE962B")) +
        geom_label(aes(label = paste0(value, "/", valeur_max)), fill = "white", size = 5) +
        theme(axis.line = element_blank()) +
        theme_bw() +
        theme(panel.grid.major.x  = element_line(color = "grey90"),
              panel.grid.major.y = element_blank()) +
        theme(panel.grid.minor.x = element_line(color = "grey90"),
              panel.grid.minor.y = element_blank()) +
        theme(
          axis.title.y = element_blank(),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 15),
          strip.text = element_text(size = 12, face = "bold")
        ) +
        theme(strip.background = element_rect(fill = "white", color = "black", size = 2)) +
        theme(axis.text = element_text(size = 12, color = "black"), axis.title = element_text(size = 15, face = "bold")) +
        guides(fill = FALSE) +
        labs(fill = "Dimension", y = "Valeur de l'indicateur / valeur max") +
        theme(legend.position = "top") +
        coord_flip()
    }

    list_indicators <- map2(dim_indic$dimension2, dim_indic$data, indic_plot)
    names(list_indicators) <- paste0("indic_", unique(dim_indic$dimension2))

    return(c(splotlist, list_indicators))
  }

  if (IDEAdata$input.type == "single") {
    res_dim <- IDEAdata$dataset %>% mutate(dimension = str_remove_all(dimension, "Durabilité "))
    label_nodes <- label_nodes %>% mutate(dimension = str_remove_all(dimension, "Durabilité "))
    return_plot <- list()
    nom <- unique(res_dim$id_exploit)
    return_plot[[nom]] <- singleplots(res_dim)
  }

  if (IDEAdata$input.type == "folder") {
    res_dim <- IDEAdata$dataset %>%
      mutate(dimension = str_remove_all(dimension, "Durabilité ")) %>%
      group_by(id_exploit) %>%
      nest()
    label_nodes <- label_nodes %>% mutate(dimension = str_remove_all(dimension, "Durabilité "))

    return_plot <- map(res_dim$data, singleplots)
    names(return_plot) <- res_dim$id_exploit
  }

  return_plot$input.type <- IDEAdata$input.type
  return_plot$plot.type <- "dim"
  return(return_plot)
}
