#' Render a PDF report of an IDEA diagnosis
#'
#' @param IDEAdata output generated by an `importIDEA()` call
#' @param file the output file name. Should end by ".pdf"
#' @param file the file name with no extension
#' @param silent Should the algorithm be silent ?
#'
#' @return A PDF report
#' @import rmarkdown
#' @import rmarkdown
#' @import tidyr
#' @import dplyr
#' @import stringr
#' @import tibble
#' @import knitr
#' @import ggplot2
#' @import cli
#' @export
#'
#' @examples
#' library(IDEATools)
#' path <- system.file("", package = "IDEATools")
#' MakeGroupReport(path)
MakeGroupReport <- function(input, output_dir = getwd(), file = "Rapport_groupe", silent = FALSE) {

  Encoding(list_max_compo$composante) <- "UTF-8"

  if (!dir.exists(output_dir)) {
    dir.create(output_dir)
  }

  IDEAdata <- importIDEA(input)

  outdir <- tempdir()

  template <- system.file("report/rapport_groupe.Rmd", package = "IDEATools")

  style_folder <- system.file("report/bandeau.png", package = "IDEATools")

  # Définition des paramètres pour le rendu
  params <- list(data = IDEAdata,
                 outdir = outdir,
                 anon = FALSE)


  output_file <- paste0(file,"_",Sys.Date(),".pdf")

  # Rendu du document dans un sous-environnement isolé
  suppressWarnings(render(template, output_file = output_file, output_dir = output_dir,
                          params = params,
                          envir = new.env(parent = globalenv()), quiet = FALSE))


  if(!silent){
    cat_bullet(paste0("Le rapport a été exporté à l'adresse '",file.path(output_dir,file),".pdf'"), bullet = "info", bullet_col = "green")
  }

}




