#' Render a PDF report of an IDEA diagnosis
#'
#' @param IDEAdata output generated by an `importIDEA()` call
#' @param file the output file name. Should end by ".pdf"
#' @param silent Should the algorithm be silent ?
#'
#' @return A PDF report
#' @import rmarkdown
#' @export
#'
#' @examples
#' library(IDEATools)
#' path <- system.file("example_json.json", package = "IDEATools")
#' IDEAdata <- importIDEA(path, anonymous = FALSE)
#' MakeReport(IDEAdata)
MakeReport <- function(IDEAdata, file = paste0("Rapport_", Sys.Date(),".pdf"), silent = FALSE) {

  outdir <- tempdir()

  exportIDEA(MakeTrees(IDEAdata), outdir = outdir)

  template <- system.file("report/rapport_individuel.Rmd", package = "IDEATools")

  style_folder <- system.file("report/bandeau.png", package = "IDEATools")

  # Définition des paramètres pour le rendu
  params <- list(data = IDEAdata,
                 outdir = outdir,
                 anon = FALSE)


  # Rendu du document dans un sous-environnement isolé
  suppressWarnings(render(template, output_file = file, output_dir = getwd(),
         params = params,
         envir = new.env(parent = globalenv()), quiet = FALSE))


  if(!silent){
    cat(paste0("Le rapport a été exporté sous le nom de '",file,"' dans votre répertoire de travail.\n"))
  }

}




