#' Generate adequate plots for group analysis with the IDEA method
#'
#' @param IDEAdata output generated by an `importIDEA()` call
#'
#' @return a named list of plots
#' @importFrom magrittr %>%
#' @importFrom dplyr n_distinct mutate inner_join arrange case_when distinct bind_rows filter
#' @import ggplot2
#' @importFrom ggrepel geom_label_repel
#' @importFrom ggpubr theme_pubr
#' @importFrom readr parse_number
#' @importFrom tidyr gather
#' @export
#'
#' @examples
#' library(IDEATools)
#' path <- system.file("", package = "IDEATools")
#' IDEAdata <- importIDEA(path, anonymous = FALSE)
#' IDEAres <- metaIDEA(IDEAdata)
metaIDEA <- function(IDEAdata) {
  if (IDEAdata$input.type == "single") {
    stop("Erreur: les données d'entrée ne correspondent pas à un collectif")
  }
  if (n_distinct(IDEAdata$dataset$id_exploit) < 2) {
    stop("Erreur: le nombre d'exploitations doit être supérieur ou égal à 2")
  }

  return_plot <- list()

  nodes <- IDEAdata$nodes

  heat_data <- nodes$Global %>%
    gather(key = indicateur, value = resultat, -id_exploit) %>%
    mutate(indicateur = replace_indicateur(indicateur)) %>%
    inner_join(label_nodes, by = c("indicateur" = "code_indicateur")) %>%
    mutate(resultat = factor(resultat, levels = c("très favorable", "favorable", "intermédiaire", "défavorable", "très défavorable", "NC"))) %>%
    mutate(nom_indicateur = ifelse(nom_indicateur == "Capacité productive et reproductive de biens et de services", yes = "Capacité productive et \n reproductive de biens et de \n services", no = nom_indicateur)) %>%
    mutate(num_indic = parse_number(indicateur)) %>%
    arrange(dim, num_indic) %>%
    mutate(indicateur = factor(indicateur, levels = unique(indicateur))) %>%
    mutate(level = case_when(
      level == "indicateur" ~ "Indicateur",
      level == "propriete" ~ "Propriété"
    ))

  dim <- IDEAdata$dataset %>% distinct(id_exploit, dimension, dimension_value)

  n_exploit <- n_distinct(dim$id_exploit)

  df_compo <- IDEAdata$dataset %>%
    distinct(id_exploit,dimension,composante,composante_value)%>%
    inner_join(list_max_compo, by = "composante") %>%
    mutate(dimension = factor(dimension, levels = c("Agroécologique","Socio-Territoriale","Economique")))

  ae_levels <- c("Diversité fonctionnelle", "Bouclage de flux de matières et d'énergie \npar une recherche d'autonomie", "Sobriété dans l'utilisation des ressources", "Assurer des conditions favorables à la production\n à moyen et long terme", "Réduire les impacts sur la santé humaine et les écosystèmes")

  st_levels <- c("Alimentation", "Développement local \net économie circulaire", "Emploi et qualité au travail", "Ethique et développement humain")

  ec_levels <- c("Viabilité économique et financière", "Indépendance", "Transmissibilité", "Efficience globale")

  glob_levels <- c(ae_levels, st_levels, ec_levels)

  df_compo2 <- df_compo %>%
    mutate(composante = ifelse(composante == "Assurer des conditions favorables à la production à moyen et long terme",
                               yes = "Assurer des conditions favorables à la production\n à moyen et long terme", no = composante
    )) %>%
    mutate(composante = ifelse(composante == "Bouclage de flux \nde matières et d'énergie \npar une recherche d'autonomie",
                               yes = "Bouclage de flux de matières et d'énergie \npar une recherche d'autonomie", no = composante
    )) %>%
    arrange(dimension, composante) %>%
    mutate(composante = factor(composante, levels = glob_levels)) %>%
    mutate(dim_num = as.numeric(dimension)) %>%
    mutate(compo_num = as.numeric(composante)) %>%
    mutate(min_compo = 0)

  df_indic <- IDEAdata$dataset %>%
    distinct(id_exploit,dimension,indicateur,value)%>%
    inner_join(list_max, by = "indicateur") %>%
    inner_join(label_nodes %>% select(code_indicateur,nom_complet),by = c("indicateur"="code_indicateur")) %>%
    mutate(dimension = factor(dimension, levels = c("Agroécologique","Socio-Territoriale","Economique"))) %>%
    mutate(indic_no = parse_number(nom_complet)) %>%
    arrange(dimension,indic_no) %>%
    mutate(nom_complet = factor(nom_complet, levels = unique(nom_complet)))


  dim2 <- bind_rows(dim %>% mutate(dimension_value = 100 - dimension_value) %>% mutate(alpha = "a"), dim %>% mutate(alpha = "b")) %>%
    arrange(id_exploit, dimension) %>%
    mutate(label = ifelse(alpha == "a", yes = "", no = paste0(dimension_value, "/100")))




  return_plot$metaProp <- ggplot(heat_data %>% filter(level == "Propriété"), aes(id_exploit, nom_indicateur, fill = resultat)) +
    geom_tile(color = "black") +
    scale_fill_manual(values = c("favorable" = "#1CDA53", "défavorable" = "#FF6348", "intermédiaire" = "#FFA300", "très défavorable" = "#FF0000", "très favorable" = "#0D8A00", "NC" = "#A0A0A0"), drop = FALSE) +
    labs(x = "Exploitation", y = "Propriété", fill = "Evaluation") +
    theme_pubr() +
    theme(axis.text.y = element_text(color = "black", size = 13), axis.title = element_text(size = 17, face = "bold"), legend.text = element_text(size = 13), legend.title = element_text(size = 15), legend.position = "top") +
    theme(axis.text.x = element_text(color = "black", size = 11, angle = 90)) +
    theme(plot.background = element_rect(color = "transparent")) +
    theme(strip.text = element_text(size = 12, face = "bold", color = "black")) +
    theme(strip.background = element_rect(color = "black", fill = "white"))


  return_plot$metaIndic <- ggplot(heat_data %>% filter(level == "Indicateur"), aes(id_exploit, indicateur, fill = resultat)) +
    geom_tile(color = "black") +
    scale_fill_manual(values = c("favorable" = "#1CDA53", "défavorable" = "#FF6348", "intermédiaire" = "#FFA300", "très défavorable" = "#FF0000", "très favorable" = "#0D8A00", "NC" = "#A0A0A0"), drop = FALSE) +
    labs(x = "Exploitation", y = "Indicateur", fill = "Evaluation") +
    theme_pubr() +
    theme(axis.text.y = element_text(color = "black", size = 12), axis.title = element_text(size = 17, face = "bold"), legend.text = element_text(size = 13), legend.title = element_text(size = 15), legend.position = "top") +
    theme(axis.text.x = element_text(color = "black", size = 13, angle = 90)) +
    theme(plot.background = element_rect(color = "transparent")) +
    theme(strip.text = element_text(size = 12, face = "bold", color = "black")) +
    theme(strip.background = element_rect(color = "black", fill = "white"))



  return_plot$metaDim <- ggplot(dim2, aes(x = id_exploit, y = dimension_value, label = label, fill = dimension, alpha = alpha)) +
    scale_alpha_manual(values = c(0.6, 1)) +
    guides(alpha = FALSE) +
    geom_col(color = "black") +
    geom_text(aes(x = id_exploit, y = dimension_value, label = label), position = position_stack(vjust = 0.5)) +
    scale_fill_manual(values = c("Agroécologique" = "#2e9c15", "Socio-Territoriale" = "#469FF9", "Economique" = "#FE962B"), drop = FALSE) +
    theme_bw() +
    ylim(0, 300) +
    labs(x = "Exploitation", y = "Score", fill = "Evaluation") +
    theme(
      axis.title = element_text(size = 17),
      legend.text = element_text(size = 13),
      legend.title = element_text(size = 15),
      strip.text = element_text(size = 9, face = "bold")
    ) +
    theme(axis.text = element_text(size = 13, color = "black")) +
    theme(strip.background = element_rect(fill = "white", color = "black")) +
    theme(legend.position = "bottom") +
    coord_flip()

  moys <- dim %>% group_by(dimension) %>% summarise(Moyenne = mean(dimension_value))

  return_plot$boxplot_dim <- ggplot(dim, aes(x = dimension, y = dimension_value)) +
    stat_boxplot(geom = "errorbar", width = 0.3) +
    geom_boxplot(color = "black", aes(fill = dimension), width = 0.8) +
    geom_point(data = moys, aes(x = dimension, y = Moyenne), size = 4, color = "darkred",shape = 18) +
    ggrepel::geom_label_repel(data = moys, aes(x = dimension, y = Moyenne, label = paste0("Moyenne = ",round(Moyenne,1))), nudge_x = 0.5, nudge_y = 5) +
    theme_tq_cust() +
    scale_fill_manual(values = c("Agroécologique" = "#2e9c15", "Socio-Territoriale" = "#5077FE", "Economique" = "#FE962B")) +
    theme(axis.title.x = element_blank()) +
    labs(y = "Valeur de la dimension",fill = "Dimension", caption = paste0("(N = ",n_exploit,")")) +
    scale_y_continuous(breaks = seq(0,100,10), limits = c(0,100))




  moys <- df_compo2 %>% group_by(dimension,composante) %>% summarise(Moyenne = mean(composante_value)) %>%
    mutate(compo_num = as.numeric(composante))

  return_plot$boxplot_compo <- ggplot(df_compo2, aes(x = reorder(composante,-compo_num), y = composante_value)) +
    stat_boxplot(geom = "errorbar", width = 0.3) +
    geom_boxplot(color = "black", aes(fill = dimension), width = 0.8) +
    geom_point(data = moys, aes(x = reorder(composante,-compo_num), y = Moyenne,color = "Moyenne"), size = 4, shape = 18) +
    geom_point(aes(y = max_compo),shape = 93, size = 5, color = "red") +
    geom_point(aes(y = min_compo),shape = 91, size = 5, color = "red") +
    theme_tq_cust() +
    scale_fill_manual(values = c("Agroécologique" = "#2e9c15", "Socio-Territoriale" = "#5077FE", "Economique" = "#FE962B")) +
    scale_color_manual(values = c("darkred")) +
    theme(axis.title.y = element_blank()) +
    labs(y= "Valeur de la composante",fill = "Dimension", color = "Légende", caption = paste0("(N = ",n_exploit,")")) +
    coord_flip() +
    guides(fill = FALSE) +
    facet_wrap(~dimension, ncol = 1, scales = 'free', drop = TRUE) +
    scale_y_continuous(breaks = seq(0,100,5))



  dat <- IDEAdata$dataset %>% filter(dimension == "Agroécologique") %>% select(composante,indicateur,value, composante_value) %>%
    inner_join(list_max, by = "indicateur") %>%
    inner_join(label_nodes %>% select(code_indicateur,nom_complet),by = c("indicateur"="code_indicateur")) %>%
    mutate(composante = ifelse(composante == "Assurer des conditions favorables à la production à moyen et long terme",
                               yes = "Assurer des conditions favorables à la production\n à moyen et long terme", no = composante
    )) %>%
    mutate(composante = ifelse(composante == "Bouclage de flux \nde matières et d'énergie \npar une recherche d'autonomie",
                               yes = "Bouclage de flux de matières et d'énergie \npar une recherche d'autonomie", no = composante
    )) %>%
    mutate(composante = factor(composante, levels = glob_levels)) %>%
    mutate(indic_no = parse_number(nom_complet)) %>%
    arrange(composante,indic_no) %>%
    rowwise() %>%
    mutate(nom_complet = wrapit(nom_complet)) %>%
    ungroup() %>%
    mutate(nom_complet = factor(nom_complet, levels = unique(nom_complet)))

  moys <- dat %>% group_by(composante,nom_complet,indic_no) %>% summarise(Moyenne = mean(value))

  return_plot$boxplot_AE <- ggplot(dat, aes(x = reorder(nom_complet,-indic_no), y = value)) +
    stat_boxplot(geom = "errorbar", width = 0.3) +
    geom_boxplot(color = "black",fill = "#2e9c15", width = 0.8) +
    geom_point(aes(y = 0),shape = 91, size = 5, color = "red") +
    geom_point(aes(y = valeur_max),shape = 93, size = 5, color = "red") +
    geom_point(data = moys, aes(x = reorder(nom_complet,-indic_no), y = Moyenne,color = "Moyenne"), size = 4, shape = 18) +
    scale_color_manual(values = "darkred") +
    coord_flip()+
    facet_wrap(~composante, ncol = 1, scales = "free") +
    theme_tq_cust() +
    scale_y_continuous(breaks = seq(0,10,1)) +
    labs(x = "Indicateurs regroupés par composante", y = "Valeur de l'indicateur", color = "Légende", caption = paste0("(N = ",n_exploit,")"))

  dat <- IDEAdata$dataset %>% filter(dimension == "Socio-Territoriale") %>% select(composante,indicateur,value, composante_value) %>%
    inner_join(list_max, by = "indicateur") %>%
    inner_join(label_nodes %>% select(code_indicateur,nom_complet),by = c("indicateur"="code_indicateur")) %>%
    mutate(composante = ifelse(composante == "Assurer des conditions favorables à la production à moyen et long terme",
                               yes = "Assurer des conditions favorables à la production\n à moyen et long terme", no = composante
    )) %>%
    mutate(composante = ifelse(composante == "Bouclage de flux \nde matières et d'énergie \npar une recherche d'autonomie",
                               yes = "Bouclage de flux de matières et d'énergie \npar une recherche d'autonomie", no = composante
    )) %>%
    mutate(composante = factor(composante, levels = glob_levels)) %>%
    mutate(indic_no = parse_number(nom_complet)) %>%
    arrange(composante,indic_no) %>%
    rowwise() %>%
    mutate(nom_complet = wrapit(nom_complet)) %>%
    ungroup() %>%
    mutate(nom_complet = factor(nom_complet, levels = unique(nom_complet)))

  moys <- dat %>% group_by(composante,nom_complet,indic_no) %>% summarise(Moyenne = mean(value))

  return_plot$boxplot_ST <- ggplot(dat, aes(x = reorder(nom_complet,-indic_no), y = value)) +
    stat_boxplot(geom = "errorbar", width = 0.3) +
    geom_boxplot(color = "black",fill = "#5077FE", width = 0.8) +
    geom_point(aes(y = 0),shape = 91, size = 5, color = "red") +
    geom_point(aes(y = valeur_max),shape = 93, size = 5, color = "red") +
    scale_color_manual(values = "darkred") +
    geom_point(data = moys, aes(x = reorder(nom_complet,-indic_no), y = Moyenne,color = "Moyenne"), size = 4, shape = 18) +
    coord_flip()+
    facet_wrap(~composante, ncol = 1, scales = "free") +
    theme_tq_cust() +
    scale_y_continuous(breaks = seq(0,10,1)) +
    labs(x = "Indicateurs regroupés par composante", y = "Valeur de l'indicateur", color = "Légende", caption = paste0("(N = ",n_exploit,")"))


  dat <- IDEAdata$dataset %>% filter(dimension == "Economique") %>% select(composante,indicateur,value, composante_value) %>%
    inner_join(list_max, by = "indicateur") %>%
    inner_join(label_nodes %>% select(code_indicateur,nom_complet),by = c("indicateur"="code_indicateur")) %>%
    mutate(composante = ifelse(composante == "Assurer des conditions favorables à la production à moyen et long terme",
                               yes = "Assurer des conditions favorables à la production\n à moyen et long terme", no = composante
    )) %>%
    mutate(composante = ifelse(composante == "Bouclage de flux \nde matières et d'énergie \npar une recherche d'autonomie",
                               yes = "Bouclage de flux de matières et d'énergie \npar une recherche d'autonomie", no = composante
    )) %>%
    mutate(composante = factor(composante, levels = glob_levels)) %>%
    mutate(indic_no = parse_number(nom_complet)) %>%
    arrange(composante,indic_no) %>%
    rowwise() %>%
    mutate(nom_complet = wrapit(nom_complet)) %>%
    ungroup() %>%
    mutate(nom_complet = factor(nom_complet, levels = unique(nom_complet)))

  moys <- dat %>% group_by(composante,nom_complet,indic_no) %>% summarise(Moyenne = mean(value))

  return_plot$boxplot_EC <- ggplot(dat, aes(x = reorder(nom_complet,-indic_no), y = value)) +
    stat_boxplot(geom = "errorbar", width = 0.3) +
    geom_boxplot(color = "black",fill = "#FE962B", width = 0.8) +
    geom_point(aes(y = 0),shape = 91, size = 5, color = "red") +
    geom_point(aes(y = valeur_max),shape = 93, size = 5, color = "red") +
    scale_color_manual(values = "darkred") +
    geom_point(data = moys, aes(x = reorder(nom_complet,-indic_no), y = Moyenne,color = "Moyenne"), size = 4, shape = 18) +
    coord_flip()+
    facet_wrap(~composante, ncol = 1, scales = "free") +
    theme_tq_cust() +
    scale_y_continuous(breaks = seq(0,10,1)) +
    labs(x = "Indicateurs regroupés par composante", y = "Valeur de l'indicateur", color = "Légende", caption = paste0("(N = ",n_exploit,")"))


  return_plot$input.type <- IDEAdata$input.type
  return_plot$plot.type <- "meta"
  return_plot$n_exploit <- n_distinct(IDEAdata$dataset$id_exploit)

  return(return_plot)
}
