#' Generate polarised plots for components
#'
#' @param IDEAdata output generated by an `importIDEA()` call
#'
#' @return a named list of plots
#' @importFrom magrittr %>%
#' @importFrom dplyr mutate case_when arrange desc inner_join filter select rowwise ungroup group_by
#' @importFrom ggplot2 ggplot aes geom_rect geom_col theme_bw geom_text scale_fill_manual theme element_blank element_text scale_y_continuous labs coord_polar geom_vline xlim
#' @importFrom ggpubr ggtexttable ttheme colnames_style rownames_style tbody_style ggarrange
#' @importFrom glue glue
#' @importFrom purrr map
#' @importFrom readr parse_number
#' @importFrom stringr str_remove_all
#' @importFrom tidyr nest
#' @importFrom tibble tribble
#' @importFrom ggimage geom_image
#' @import pdftools
#' @export
#'
#' @examples
#' library(IDEATools)
#' path <- system.file("example_json.json", package = "IDEATools")
#' IDEAdata <- importIDEA(path, anonymous = FALSE)
#' IDEAres <- PolarComponent(IDEAdata)
PolarComponent <- function(IDEAdata) {


  # PDF temporaire
  temp_pdf <- file.path(tempdir(),"plot.pdf")


  Encoding(list_max_compo$composante) <- "UTF-8"

  singleplots <- function(dataset) {

    component_data <- dataset %>% distinct(composante,dimension,composante_value) %>%
      inner_join(list_max_compo, by = "composante") %>%
      mutate(score = round(composante_value/max_compo*100)) %>%
      mutate(composante = factor(composante, levels = unique(list_max_compo$composante))) %>%
      mutate(dimension = factor(dimension, levels = c("Agroécologique","Socio-Territoriale","Economique"))) %>%
      select(variable = composante, performance = dimension, value = score) %>%
      mutate(variable = factor(variable, levels = unique(variable)))



    ## Premier plot : Le radar qui est exporté en pdf
    ggplot(component_data, aes(x = variable, y = value, fill = performance)) +
      geom_rect(xmin = 0, xmax = 13, ymin = -3, ymax = 0, fill = "black") +
      geom_col(color = "black", width = 1) +
      geom_vline(xintercept = c(seq(0.5,13.5,1)), color = "black") +
      geom_hline(yintercept = c(0,20,40,60,80,100), color = "black") +
      geom_label(x = 0.5, y = 20, label = "20%", size = 5,inherit.aes = FALSE) +
      geom_label(x = 0.5, y = 40, label = "40%", size = 5,inherit.aes = FALSE) +
      geom_label(x = 0.5, y = 60, label = "60%", size = 5,inherit.aes = FALSE) +
      geom_label(x = 0.5, y = 80, label = "80%", size = 5,inherit.aes = FALSE) +
      scale_fill_manual(values = c("Agroécologique"="#2e9c15","Socio-Territoriale"="#5077FE", "Economique"="#FE962B")) +
      coord_polar() +
      ylim(-3,100) +
      theme(panel.background = element_blank(),
            panel.border = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            axis.title = element_blank()) +
      guides(fill = FALSE) +
      ggsave(temp_pdf, dpi = "retina",width = 10.1, height = 7.53)


    ## Préparation du donut
    donut_data <- data.frame(
      category=c("Agroécologique", "Socio-Territoriale", "Economique"),
      count=c(38.46, 30.7, 30.7)
    )
    donut_data$fraction = donut_data$count / sum(donut_data$count)
    donut_data$ymax = cumsum(donut_data$fraction)
    donut_data$ymin = c(0, head(donut_data$ymax, n=-1))


    img_folder <- system.file("img", package = "IDEATools")


    path_tab <- tibble::tribble(
      ~composante, ~chemin,
      "Diversité fonctionnelle", "picto_div.png",
      "Bouclage de flux \nde matières et d'énergie \npar une recherche d'autonomie", "picto_flux.png",
      "Sobriété dans l'utilisation des ressources", "picto_ressources.png",
      "Assurer des conditions favorables à la production à moyen et long terme", "picto_production.png",
      "Réduire les impacts sur la santé humaine et les écosystèmes", "picto_sante.png",
      "Alimentation", "picto_alimentation.png",
      "Développement local \net économie circulaire", "picto_circulaire.png",
      "Emploi et qualité au travail", "picto_emploi.png",
      "Ethique et développement humain", "picto_ethique.png",
      "Viabilité économique et financière", "picto_economique.png",
      "Indépendance", "picto_independance.png",
      "Transmissibilité", "picto_transmissibilite.png",
      "Efficience globale", "picto_efficience.png"
    ) %>%
      rowwise() %>%
      mutate(chemin = file.path(img_folder,chemin)) %>%
      ungroup()


    path_data <- component_data %>% mutate(ordre = 1:13) %>% inner_join(path_tab, by = c("variable"="composante")) %>% arrange(ordre)


    # Make the plot
    p <- ggplot(donut_data, aes(ymax=ymax, ymin=ymin, xmax=3.45, xmin=3, label = category)) +
      geom_image(aes(x = 2.0,y = 1),image = temp_pdf, size = I(0.46)) +
      geom_rect(aes(fill=category), color = "black", alpha = 0.6) +
      geom_image(aes(x = 3.35, y = 0.1823), image = file.path(img_folder,"TEXT_AE.png"),size = I(0.13), color = "#2e9c15") +
      geom_image(aes(x = 3.45, y = 0.5431), image = file.path(img_folder,"TEXT_ST.png"),size = I(0.27), color = "#5077FE") +
      geom_image(aes(x = 3.45, y = 0.8451), image = file.path(img_folder,"TEXT_ECO.png"),size = I(0.15), color = "#FE962B") +

      geom_image(aes(x = 3.225, y = 0.15/4), image = path_data$chemin[1],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.23/4*2), image = path_data$chemin[2],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.19), image = path_data$chemin[3],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.27), image = path_data$chemin[4],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.34), image = path_data$chemin[5],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.42), image = path_data$chemin[6],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.499), image = path_data$chemin[7],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.575), image = path_data$chemin[8],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.66), image = path_data$chemin[9],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.735), image = path_data$chemin[10],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.805), image = path_data$chemin[11],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.885), image = path_data$chemin[12],size = I(0.05)) +
      geom_image(aes(x = 3.225, y = 0.965), image = path_data$chemin[13],size = I(0.05)) +
      coord_polar(theta="y") +
      scale_fill_manual(values = c("Agroécologique"="#2e9c15","Socio-Territoriale"="#5077FE", "Economique"="#FE962B")) +
      ggplot2::xlim(c(2, 4.9)) +
      ggplot2::theme_void() +
      guides(fill = FALSE) +
      ggplot2::theme(plot.margin=unit(c(-5,-5,-5,-5),"cm"))

    return(p)


  }


  if (IDEAdata$input.type == "single") {
    dataset <- IDEAdata$dataset
    return_plot <- list()
    nom <- unique(dataset$id_exploit)
    return_plot[[nom]] <- singleplots(dataset)
  }

  if (IDEAdata$input.type == "folder") {
    dataset <- IDEAdata$dataset %>%
      dplyr::group_by(id_exploit) %>%
      tidyr::nest()

    return_plot <- purrr::map(dataset$data, singleplots)
    names(return_plot) <- dataset$id_exploit
  }

  return_plot$input.type <- IDEAdata$input.type
  return_plot$plot.type <- "PolarComponent"

  return(return_plot)

}

